version: "3.7"

services:
  influxdb2:
    container_name: influxdb2
    image: influxdb:latest
    network_mode: "bridge"
    ports:
      - "8086:8086"
    volumes:
      - type: bind
        source: ./tmp/influxdb2/data
        target: /var/lib/influxdb2
      - type: bind
        source: ./tmp/influxdb2/config
        target: /etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=$$DOCKER_INFLUXDB_INIT_MODE
      - DOCKER_INFLUXDB_INIT_USERNAME=$$DOCKER_INFLUXDB_INIT_USERNAME
      - DOCKER_INFLUXDB_INIT_PASSWORD=$$DOCKER_INFLUXDB_INIT_PASSWORD
      - DOCKER_INFLUXDB_INIT_ORG=$$DOCKER_INFLUXDB_INIT_ORG
      - DOCKER_INFLUXDB_INIT_BUCKET=$$DOCKER_INFLUXDB_INIT_BUCKET
      - DOCKER_INFLUXDB_INIT_RETENTION=$$DOCKER_INFLUXDB_INIT_RETENTION
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
    restart: always
